 PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#> 
 PREFIX  foaf: <http://xmlns.com/foaf/0.1/> 
 PREFIX  dbprop: <http://dbpedia.org/property/> 
 PREFIX  dbpedia: <http://dbpedia.org/ontology/>  
 SELECT DISTINCT  ?artist ?artistName ?occupation ?shortDescription ?birthdate ?photo 
    WHERE   { 
            ?artist <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> dbpedia:Artist .
                 ?artist rdfs:label ?artistName     
        OPTIONAL       { 
                ?artist dbpedia:birthDate ?birthdate 
        }     
        OPTIONAL       { 
                ?artist dbprop:occupation ?occupation         
        FILTER isLiteral(?occupation)       
        }     
        OPTIONAL       { 
                ?artist dbprop:shortDescription ?shortDescription 
        }     
        OPTIONAL       { 
                ?artist dbpedia:thumbnail ?photo 
        }     
        FILTER regex(?artistName, "clive owen", "i")     
        FILTER ( lang(?artistName) = "en" )   
        } 
