
 SELECT DISTINCT  ?subject ?predicate ?object 
    WHERE   {   { <http://dbpedia.org/resource/Barnaby_Rudge> ?predicate ?object 
    }     
        UNION       
        { 
            ?subject ?predicate <http://dbpedia.org/resource/Barnaby_Rudge> 
    }     
    FILTER ( ( lang(?object) = "en" ) || ( lang(?object) = "" ) )   
    } 
    ORDER BY ?predicate ?subject OFFSET  0 
    LIMIT   200 
 